# Verwende das Node.js-Image als Basis
FROM node:18

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Kopiere die package.json und package-lock.json
COPY package*.json ./

# Installiere die Abhängigkeiten
RUN npm install

# Kopiere den gesamten Quellcode
COPY . .

# Exponiere Port 3000
EXPOSE 3000

# Starte die Entwicklungsumgebung
CMD ["npm", "start"]
